import { FileText, Download, Filter } from 'lucide-react';
import './Reports.css';

const Reports = () => {
  const pastReports = [];

  return (
    <div className="reports-page">
      <div className="page-header-actions">
        <div>
          <h1>Past Reports</h1>
          <p>Access and download previously generated fraud analysis reports.</p>
        </div>
        <button className="btn-primary flex-center gap-2" style={{ backgroundColor: 'var(--bg-card)', color: 'var(--text-primary)', border: '1px solid var(--border-color)' }}>
          <Filter size={18} /> Filter Reports
        </button>
      </div>

      <div className="card table-container">
        <div className="table-wrapper">
          <table className="reports-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Date Generated</th>
                <th>Total Documents</th>
                <th>Matches</th>
                <th>Fraud Alerts</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {pastReports.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
                    No reports available.
                  </td>
                </tr>
              ) : (
                pastReports.map((report) => (
                  <tr key={report.id}>
                    <td>
                      <div className="report-id-cell">
                        <FileText size={16} className="text-secondary" />
                        <span className="font-medium">{report.id}</span>
                      </div>
                    </td>
                    <td>{report.date}</td>
                    <td>{report.totalDocs}</td>
                    <td className="green-text font-medium">{report.matches}</td>
                    <td className={report.fraud > 0 ? 'red-text font-medium' : ''}>{report.fraud}</td>
                    <td>{report.user}</td>
                    <td>
                      <button className="action-btn" title="Download PDF">
                        <Download size={18} />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
