import { FileText, Download, Filter } from 'lucide-react';
import './Reports.css';

const Reports = () => {
  const pastReports = [
    { id: 'REP-23-089', date: '28 Oct 2023', totalDocs: 156, matches: 142, fraud: 3, user: 'Admin User' },
    { id: 'REP-23-088', date: '27 Oct 2023', totalDocs: 98, matches: 90, fraud: 1, user: 'Admin User' },
    { id: 'REP-23-087', date: '26 Oct 2023', totalDocs: 210, matches: 195, fraud: 8, user: 'Ramesh Singh' },
    { id: 'REP-23-086', date: '25 Oct 2023', totalDocs: 45, matches: 45, fraud: 0, user: 'Admin User' },
    { id: 'REP-23-085', date: '24 Oct 2023', totalDocs: 124, matches: 110, fraud: 5, user: 'Suresh Kumar' },
  ];

  return (
    <div className="reports-page">
      <div className="page-header-actions">
        <div>
          <h1>Past Reports</h1>
          <p>Access and download previously generated fraud analysis reports.</p>
        </div>
        <button className="btn-primary flex-center gap-2" style={{ backgroundColor: 'var(--bg-card)', color: 'var(--text-primary)', border: '1px solid var(--border-color)' }}>
          <Filter size={18} /> Filter Reports
        </button>
      </div>

      <div className="card table-container">
        <div className="table-wrapper">
          <table className="reports-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Date Generated</th>
                <th>Total Documents</th>
                <th>Matches</th>
                <th>Fraud Alerts</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {pastReports.map((report) => (
                <tr key={report.id}>
                  <td>
                    <div className="report-id-cell">
                      <FileText size={16} className="text-secondary" />
                      <span className="font-medium">{report.id}</span>
                    </div>
                  </td>
                  <td>{report.date}</td>
                  <td>{report.totalDocs}</td>
                  <td className="green-text font-medium">{report.matches}</td>
                  <td className={report.fraud > 0 ? 'red-text font-medium' : ''}>{report.fraud}</td>
                  <td>{report.user}</td>
                  <td>
                    <button className="action-btn" title="Download PDF">
                      <Download size={18} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
